USE `User listing`;

ALTER TABLE users
MODIFY COLUMN password VARCHAR(255) NOT NULL;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS profile_picture VARCHAR(255) NULL;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS is_deleted TINYINT(1) NOT NULL DEFAULT 0;